Improve Error message for local artifacts
If you specify a path that doesn't exist (say if you copy paste a
command from somewhere) the error message was like this:

arash@laptop$ greaserun --runner luigi ~/does-not-exist.jar ...
INFO:root:Reading configuration from /etc/scalegrease.json
Traceback (most recent call last):
  File "/usr/bin/greaserun", line 9, in <module>
    sys.exit(runner.main(sys.argv))
  File "/usr/lib/python2.6/dist-packages/scalegrease/runner.py", line 66, in main
    run(args.runner, args.artifact, rest_argv, conf)
  File "/usr/lib/python2.6/dist-packages/scalegrease/runner.py", line 43, in run
    artifact_storage = deploy.ArtifactStorage.resolve(artifact_spec)
  File "/usr/lib/python2.6/dist-packages/scalegrease/deploy.py", line 24, in resolve
    return MavenStorage(artifact_spec)
  File "/usr/lib/python2.6/dist-packages/scalegrease/deploy.py", line 67, in __init__
    self.artifact = MavenArtifact(*self.artifact_spec.split(':'))
TypeError: __init__() takes at least 3 arguments (2 given)